spring.application.name=smartfridge

spring.datasource.url=jdbc:mysql://localhost:3306/smartfridge?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=smartfridge
spring.datasource.password=smartfridge

#Para que Hibernate no toque el esquema
spring.jpa.hibernate.ddl-auto=none

#Fuerza a Spring a ejecutar schema.sql
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.continue-on-error=false

spring.jpa.show-sql=true
spring.jpa.open-in-view=false


